Bridge/urls.py
from django.conf.urls import patterns, url

import views

urlpatterns = patterns('',
                       url(r'^snda$', views.jump_snda, name='jumpsnda'),
                       url(r'^adwo$', views.jump_adwo, name='jumpadwo'),
                       url(r'^dianxin$', views.jump_dianxin, name='jumpdianxin'),
                       )

CPCDeviceIDReport/urls.py
from django.conf.urls import patterns, url
from CPCDeviceIDReport import views

urlpatterns = patterns('',
    url(r'^$', views.query_form, name='index'),
    url(r'^(?P<queryID>[a-f0-9]{8}-([a-f0-9]{4}-){3}[a-f0-9]{12})/$', views.query),
)

hao123/urls.py
from django.conf.urls import patterns, include, url

from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'hao123.views.home', name='home'),
                       # url(r'^hao123/', include('hao123.foo.urls')),

                       # Uncomment the admin/doc line below to enable admin documentation:
                       # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

                       # Uncomment the next line to enable the admin:
                       # url(r'^admin/', include(admin.site.urls)),
                       url(r'^huadmin/', include(admin.site.urls)),
                       url(r'^337/', include('ElexTech.urls')),
                       url(r'^MT/', include('Locojoy.urls', namespace='MT')),
                       url(r'^mac_addr/', include('CPCDeviceIDReport.urls')),
                       url(r'^change_am/', include('ChangeAMSaleRep.urls')),
                       url(r'^adspend/', include('DailyAdSpend.urls')),
                       url(r'^vast/', include('VastVideo.urls')),
                       url(r'^channel/', include('Bridge.urls')),
                       )

if settings.DEBUG:
    urlpatterns += patterns('',
                            url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                                'document_root': settings.MEDIA_ROOT,
                                }),
                            url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
                                'document_root': settings.STATIC_ROOT,
                                }),
                            )

CPCDeviceIDReport/forms.py
#!/usr/bin/env python   
# -*- coding: UTF-8 -*-

import datetime, re
from django.contrib.admin import widgets 
from django import forms
class QueryForm(forms.Form):
    adID = forms.CharField(required=True, label = 'Campaign ID', max_length = 100) 
    startDate = forms.DateField(required=True, label = 'Start Date')
    endDate = forms.DateField(required=True, label = 'End Date')
    macFormat = forms.ChoiceField(required=True, label = 'Mac Address Format', choices = [('1', u'小写无冒号'),('2', u'大写无冒号'),('3', u'小写有冒号'),('4', u'大写有冒号')])


    def clean_adID(self):
        adID = self.cleaned_data['adID'].strip()
        if not re.search('^[a-f0-9]{8}-([a-f0-9]{4}-){3}[a-f0-9]{12}$', adID): 
            raise forms.ValidationError("Please input correct campaign ID!") 
        return adID 
    

CPCDeviceIDReport/views.py
# Create your views here.

import uuid, time
import os, sys, mimetypes
from django.core.servers.basehttp import FileWrapper
from django.shortcuts import render_to_response 
from django.http import HttpResponseRedirect
from django.http import HttpResponse, Http404
from CPCDeviceIDReport.forms import QueryForm
from CPCDeviceIDReport.report import generateReport

def query_form(request):
    if 'adID' in request.GET:
        form = QueryForm(request.GET)
        if form.is_valid():
            cd = form.cleaned_data
            #html = []
            #for k,v in cd.items():
            #    html.append('<tr><td>%s</td><td>%s</td></tr>' % (k, v))
            request.session['queryID'] = str(uuid.uuid1())
            request.session['adID'] = str(cd['adID'])
            request.session['startDate'] = str(cd['startDate'])
            request.session['endDate'] = str(cd['endDate'])
            request.session['macFormat'] = str(cd['macFormat'])
            return render_to_response('query_in_progress.html', 
                                      {'queryID':request.session['queryID'], 
                                       'adID': cd['adID'], 
                                       'startDate':cd['startDate'], 
                                       'endDate': cd['endDate'],
                                       'macFormat': cd['macFormat'],
                                      })
    else:
        form = QueryForm()
    return render_to_response('query_form.html', {'form': form})

def query(request, queryID):
    if request.session.get('queryLock', False):
        return HttpResponse('Busy, try again later')
    if request.session['queryID'] != queryID:
        raise Http404()


    generateReport(request.session['adID'], request.session['startDate'], request.session['endDate'], request.session['macFormat'], queryID)

    BASEDIR = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'tmp_report')
    filename = os.path.join(BASEDIR, queryID) + '.xls'
    download_name = request.session['adID'] + '.xls' 
    wrapper = FileWrapper(open(filename))
    content_type = mimetypes.guess_type(filename)[0]
    response = HttpResponse(wrapper,content_type=content_type)
    response['Content-Length'] = os.path.getsize(filename)
    response['Content-Disposition'] = "attachment; filename= {0}".format(download_name)

    return response
    
    
    

CPCDeviceIDReport/templates/query_form.html
<html>
<head>
    {% load staticfiles %}
    <title>Get mac_address report for Campaing</title> 
    <link rel="stylesheet" href="{% static "themes/base/jquery.ui.all.css" %}">
    <script src="{% static "jquery-2.0.0.min.js" %}" ></script>
    <script src="{% static "ui/jquery.ui.core.js" %}"></script>
    <script src="{% static "ui/jquery.ui.widget.js" %}"></script>
    <script src="{% static "ui/jquery.ui.datepicker.js" %}"></script>
    <script>
    $(function() {
        $( "#id_startDate" ).datepicker({ dateFormat: 'yy-mm-dd' });
        $( "#id_endDate" ).datepicker({ dateFormat: 'yy-mm-dd' });
    });
    </script>
</head>
<body>
    <h1>Get mac_address report for CPC campaign</h1>

    {% if form.errors %}
         <p style="color: red;">
             Please correct the error{{ form.errors|pluralize }} below. 
         </p>
    {% endif %}
    <form action="" method="get"> 
        <table>
            {{ form.as_table }} 
        </table>
        <input type="submit" value="Submit">
    </form>
</body>
</html>

CPCDeviceIDReport/templates/query_in_progress.html
<html>
<head>
    {% load staticfiles %}
    <title>Get mac_address report for Campaing</title> 
    <script src="{% static "jquery-2.0.0.min.js" %}" ></script>
    <script>
    var downloadURL = function downloadURL(url) {
        var hiddenIFrameID = 'hiddenDownloader',
            iframe = document.getElementById(hiddenIFrameID);
        $("#loading").show();
        iframe.src = url;
        iframe.onload = function() {
            $("#loading").hide();
        };
    };
    $(function() {
        $(document).ajaxStart(function(){
             $("#loading").show();
         }).ajaxStop(function(){
             $("#loading").hide();
         });
        downloadURL("{{ queryID }}");
        /*$.get("{{ queryID }}");*/
        
    });
    </script>
</head>
<body>
    <h1>Get mac_address report for CPC campaign: {{ adID }}</h1>
    <h2> Start Date: {{ startDate }} </h2>
    <h2> End Date: {{ endDate }} </h2>
    <div id="loading" style=" display:none">
            <img src="{% static "loading.gif" %}" alt="Loading" />
            <iframe id="hiddenDownloader" style=" display:none"></iframe>
    </div>  

</body>
</html>